CREATE TABLE SIRIMA.PERIODE_PENERIMAAN (
	nomor SMALLINT NOT NULL,
	tahun CHAR(4) NOT NULL,
	PRIMARY_KEY(nomor, tahun)
);

CREATE TABLE SIRIMA.PROGRAM_STUDI(
	kode SERIAL NOT NULL,
	nama VARCHAR(100) NOT NULL,
	jenis_kelas VARCHAR(50) NOT NULL,
	nama_fakultas VARCHAR(50) NOT NULL,
	jenjang CHAR(2) NOT NULL,
	PRIMARY_KEY(kode),
	FOREIGN_KEY(jenjang) REFERENCES JENJANG(nama)
	ON UPDATE CASCADE
	ON DELETE RESTRICT
);

CREATE TABLE SIRIMA.PENDAFTARAN(
	id SERIAL NOT NULL,
	status_lulus BOOLEAN NOT NULL DEFAULT FALSE,
	status_verifikasi BOOLEAN NOT NULL DEFAULT FALSE,
	npm CHAR(10),
	pelamar VARCHAR(50) NOT NULL,
	nomor_periode SMALLINT NOT NULL,
	tahun_periode CHAR(4) NOT NULL,
	PRIMARY_KEY(id),
	FOREIGN_KEY(pelamar) REFERENCES PELAMAR(username) 
	ON UPDATE CASCADE
	ON DELETE CASCADE,
	FOREIGN_KEY(nomor_periode) REFERENCES 
	PERIODE_PENERIMAAN(nomor)
	ON UPDATE CASCADE
	ON DELETE CASCADE,
	FOREIGN_KEY(tahun_periode) REFERENCES 
	PERIODE_PENERIMAAN(tahun)
	ON UPDATE CASCADE
	ON DELETE CASCADE
);

CREATE TABLE SIRIMA.PENDAFTARAN_SEMAS(
	id_pendaftaran INT NOT NULL,
	status_hadir BOOLEAN NOT NULL,
	nilai_ujian INT NOT NULL,
	no_kartu_ujian CHAR(10) NOT NULL,
	lokasi_kota VARCHAR(100) NOT NULL,
	lokasi_tempat VARCHAR(150) NOT NULL,
	PRIMARY_KEY(id_pendaftaran),
	FOREIGN_KEY(id_pendaftaran) REFERENCES PENDAFTARAN(id)
	ON UPDATE CASCADE
	ON DELETE CASCADE,
	FOREIGN_KEY(lokasi_kota) REFERENCES LOKASI_UJIAN(kota)
	ON UPDATE CASCADE
	ON DELETE CASCADE,
	FOREIGN_KEY(lokasi_tempat) REFERENCES LOKASI_UJIAN(tempat)
	ON UPDATE CASCADE
	ON DELETE CASCADE
);

CREATE TABLE SIRIMA.PEMBAYARAN(
	id SERIAL NOT NULL,
	waktu_bayar TIMESTAMP NOT NULL,
	jumlah_bayar NUMERIC(10,2) NOT NULL,
	id_pendaftaran INT NOR NULL,
	PRIMARY_KEY(id),
	FOREIGN_KEY(id_pendaftaran) REFERENCES 
	PENDAFTARAN_SEMAS(id_pendaftaran)
	ON UPDATE CASCADE
	ON DELETE CASCADE
);

CREATE TABLE SIRIMA.PENGAWAS(
	nomor_induk VARCHAR(16) NOT NULL,
	nama VARCHAR(100) NOT NULL,
	no_telp TEXT NOT NULL,
	lokasi_kota VARCHAR(100) NOT NULL,
	lokasi_tempat VARCHAR(150) NOT NULL,
	lokasi_id SMALLINT NOT NULL,
	PRIMARY_KEY(nomor_induk),
	FOREIGN_KEY(lokasi_kota) REFERENCES RUANG_UJIAN(kota)
	ON UPDATE CASCADE
	ON DELETE CASCADE,
	FOREIGN_KEY(lokasi_tempat) REFERENCES RUANG_UJIAN(tempat)
	ON UPDATE CASCADE
	ON DELETE CASCADE,
	FOREIGN_KEY(lokasi_id) REFERENCES RUANG_UJIAN(id)
	ON UPDATE CASCADE
	ON DELETE CASCADE
);

